name: Tesla Tracker
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
permissions:
  contents: write
jobs:
  run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: pip3 install -r requirements.txt
      - run: python3 tracker.py
      - name: Save inventory
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase
          git add inventory.json
          git diff --staged --quiet || git commit -m "Update inventory"
          git push
